pluginName = Archi Collaboration Client
providerName = Archi

command.connect.name = Connect Collaboration...
command.connect.description = Connect to collaboration server for active model
command.connect.label = Connect Collaboration...

command.disconnect.name = Disconnect Collaboration
command.disconnect.description = Disconnect from collaboration server
command.disconnect.label = Disconnect Collaboration
