package io.archi.collab.auth;

public enum AuthorizationAction {
    ADMIN_MODEL_CATALOG_READ,
    ADMIN_MODEL_CREATE,
    ADMIN_MODEL_RENAME,
    ADMIN_MODEL_ACL_READ,
    ADMIN_MODEL_ACL_UPDATE,
    ADMIN_MODEL_TAG_LIST,
    ADMIN_MODEL_TAG_CREATE,
    ADMIN_MODEL_TAG_DELETE,
    ADMIN_MODEL_STATUS_READ,
    ADMIN_MODEL_REBUILD,
    ADMIN_MODEL_COMPACT,
    ADMIN_MODEL_WINDOW_READ,
    ADMIN_MODEL_INTEGRITY_READ,
    ADMIN_MODEL_DELETE,
    ADMIN_MODEL_EXPORT,
    ADMIN_MODEL_IMPORT,
    ADMIN_OVERVIEW_READ,
    MODEL_JOIN,
    MODEL_SUBMIT_OPS,
    MODEL_ACQUIRE_LOCK,
    MODEL_RELEASE_LOCK,
    MODEL_PRESENCE,
    MODEL_SNAPSHOT_READ
}
